
strictness: high

max-line-length: 140

member-warnings: true

doc-warnings: true

test-warnings: true

pylint:
  options:
    dummy-variables-rgx: _$|dummy|___

  disable:
    - bad-whitespace
    - invalid-name
    - multiple-statements
    - no-self-use
    - protected-access
    - too-many-arguments
    - too-many-branches
    - too-many-instance-attributes
    - too-many-lines
    - too-many-locals
    - too-many-statements
    - trailing-newlines
    - ungrouped-imports
    - len-as-condition
    - no-else-return

pep8:
  run: true
  disable:
    - N801
    - E203
    - E221
    - E302
    - E702

pep257:
  disable:
    - D200
    - D202
    - D203
    - D204
    - D213
    - D406
    - D413
    - D407
    - D412

pyroma:
  run: true

mccabe:
  run: false

