"""RAR constants
"""

from typing import Final

# block types: 'r'..'{'
RAR_BLOCK_MARK: Final = 0x72           #: Archive signature
RAR_BLOCK_MAIN: Final = 0x73           #: Archive header
RAR_BLOCK_FILE: Final = 0x74           #: File entry
RAR_BLOCK_OLD_COMMENT: Final = 0x75    #: RAR2 archive comment
RAR_BLOCK_OLD_EXTRA: Final = 0x76      #: RAR2 verification
RAR_BLOCK_OLD_SUB: Final = 0x77        #: RAR2 file metadata
RAR_BLOCK_OLD_RECOVERY: Final = 0x78   #: RAR2 recovery
RAR_BLOCK_OLD_AUTH: Final = 0x79       #: RAR2 authenticity
RAR_BLOCK_SUB: Final = 0x7a            #: RAR3 named subblock
RAR_BLOCK_ENDARC: Final = 0x7b         #: End of archive

# flags for RAR_BLOCK_MAIN
RAR_MAIN_VOLUME: Final = 0x0001
RAR_MAIN_COMMENT: Final = 0x0002
RAR_MAIN_LOCK: Final = 0x0004
RAR_MAIN_SOLID: Final = 0x0008
RAR_MAIN_NEWNUMBERING: Final = 0x0010
RAR_MAIN_AUTH: Final = 0x0020
RAR_MAIN_RECOVERY: Final = 0x0040
RAR_MAIN_PASSWORD: Final = 0x0080
RAR_MAIN_FIRSTVOLUME: Final = 0x0100
RAR_MAIN_ENCRYPTVER: Final = 0x0200

# flags for RAR_BLOCK_FILE
RAR_FILE_SPLIT_BEFORE: Final = 0x0001
RAR_FILE_SPLIT_AFTER: Final = 0x0002
RAR_FILE_PASSWORD: Final = 0x0004
RAR_FILE_COMMENT: Final = 0x0008
RAR_FILE_SOLID: Final = 0x0010
RAR_FILE_DICTMASK: Final = 0x00e0
RAR_FILE_DICT64: Final = 0x0000
RAR_FILE_DICT128: Final = 0x0020
RAR_FILE_DICT256: Final = 0x0040
RAR_FILE_DICT512: Final = 0x0060
RAR_FILE_DICT1024: Final = 0x0080
RAR_FILE_DICT2048: Final = 0x00a0
RAR_FILE_DICT4096: Final = 0x00c0
RAR_FILE_DIRECTORY: Final = 0x00e0
RAR_FILE_LARGE: Final = 0x0100
RAR_FILE_UNICODE: Final = 0x0200
RAR_FILE_SALT: Final = 0x0400
RAR_FILE_VERSION: Final = 0x0800
RAR_FILE_EXTTIME: Final = 0x1000
RAR_FILE_EXTFLAGS: Final = 0x2000

# flags for RAR_BLOCK_ENDARC
RAR_ENDARC_NEXT_VOLUME: Final = 0x0001
RAR_ENDARC_DATACRC: Final = 0x0002
RAR_ENDARC_REVSPACE: Final = 0x0004
RAR_ENDARC_VOLNR: Final = 0x0008

# flags common to all blocks
RAR_SKIP_IF_UNKNOWN: Final = 0x4000
RAR_LONG_BLOCK: Final = 0x8000

# Subtypes for RAR_BLOCK_OLD_SUB
RAR_OLD_SUB_OS2: Final = 0x100
RAR_OLD_SUB_UNIX: Final = 0x101
RAR_OLD_SUB_MAC: Final = 0x102
RAR_OLD_SUB_BEOS: Final = 0x103
RAR_OLD_SUB_NT: Final = 0x104
RAR_OLD_SUB_STREAM: Final = 0x105

# Host OS types
RAR_OS_MSDOS: Final = 0    #: MSDOS (only in RAR3)
RAR_OS_OS2: Final = 1      #: OS2 (only in RAR3)
RAR_OS_WIN32: Final = 2    #: Windows
RAR_OS_UNIX: Final = 3     #: UNIX
RAR_OS_MACOS: Final = 4    #: MacOS (only in RAR3)
RAR_OS_BEOS: Final = 5     #: BeOS (only in RAR3)

# Compression methods - "0".."5"
RAR_M0: Final = 0x30   #: No compression.
RAR_M1: Final = 0x31   #: Compression level `-m1` - Fastest compression.
RAR_M2: Final = 0x32   #: Compression level `-m2`.
RAR_M3: Final = 0x33   #: Compression level `-m3`.
RAR_M4: Final = 0x34   #: Compression level `-m4`.
RAR_M5: Final = 0x35   #: Compression level `-m5` - Maximum compression.

RAR_MAX_PASSWORD: Final = 127  # Max number of utf-16 chars in passwords.
RAR_MAX_KDF_SHIFT: Final = 24  # Max power-of-2 for KDF count
RAR_MAX_COMMENT: Final = 256 * 1024  # Max supported comment size

#
# RAR5 constants
#

RAR5_BLOCK_MAIN: Final = 1          #: Archive header
RAR5_BLOCK_FILE: Final = 2          #: File entry
RAR5_BLOCK_SERVICE: Final = 3       #: Non-file entry
RAR5_BLOCK_ENCRYPTION: Final = 4    #: Header encryption parameters
RAR5_BLOCK_ENDARC: Final = 5        #: Archive end

RAR5_BLOCK_FLAG_EXTRA_DATA: Final = 0x01
RAR5_BLOCK_FLAG_DATA_AREA: Final = 0x02
RAR5_BLOCK_FLAG_SKIP_IF_UNKNOWN: Final = 0x04
RAR5_BLOCK_FLAG_SPLIT_BEFORE: Final = 0x08
RAR5_BLOCK_FLAG_SPLIT_AFTER: Final = 0x10
RAR5_BLOCK_FLAG_DEPENDS_PREV: Final = 0x20
RAR5_BLOCK_FLAG_KEEP_WITH_PARENT: Final = 0x40

RAR5_MAIN_FLAG_ISVOL: Final = 0x01
RAR5_MAIN_FLAG_HAS_VOLNR: Final = 0x02
RAR5_MAIN_FLAG_SOLID: Final = 0x04
RAR5_MAIN_FLAG_RECOVERY: Final = 0x08
RAR5_MAIN_FLAG_LOCKED: Final = 0x10

RAR5_FILE_FLAG_ISDIR: Final = 0x01
RAR5_FILE_FLAG_HAS_MTIME: Final = 0x02
RAR5_FILE_FLAG_HAS_CRC32: Final = 0x04
RAR5_FILE_FLAG_UNKNOWN_SIZE: Final = 0x08

RAR5_COMPR_SOLID: Final = 0x40

RAR5_ENC_FLAG_HAS_CHECKVAL: Final = 0x01

RAR5_ENDARC_FLAG_NEXT_VOL: Final = 0x01

RAR5_XFILE_ENCRYPTION: Final = 1
RAR5_XFILE_HASH: Final = 2
RAR5_XFILE_TIME: Final = 3
RAR5_XFILE_VERSION: Final = 4
RAR5_XFILE_REDIR: Final = 5
RAR5_XFILE_OWNER: Final = 6
RAR5_XFILE_SERVICE: Final = 7

RAR5_XTIME_UNIXTIME: Final = 0x01
RAR5_XTIME_HAS_MTIME: Final = 0x02
RAR5_XTIME_HAS_CTIME: Final = 0x04
RAR5_XTIME_HAS_ATIME: Final = 0x08
RAR5_XTIME_UNIXTIME_NS: Final = 0x10

RAR5_XENC_CIPHER_AES256: Final = 0

RAR5_XENC_CHECKVAL: Final = 0x01
RAR5_XENC_TWEAKED: Final = 0x02

RAR5_XHASH_BLAKE2SP: Final = 0

RAR5_XREDIR_UNIX_SYMLINK: Final = 1
RAR5_XREDIR_WINDOWS_SYMLINK: Final = 2
RAR5_XREDIR_WINDOWS_JUNCTION: Final = 3
RAR5_XREDIR_HARD_LINK: Final = 4
RAR5_XREDIR_FILE_COPY: Final = 5

RAR5_XREDIR_ISDIR: Final = 0x01

RAR5_XOWNER_UNAME: Final = 0x01
RAR5_XOWNER_GNAME: Final = 0x02
RAR5_XOWNER_UID: Final = 0x04
RAR5_XOWNER_GID: Final = 0x08

RAR5_OS_WINDOWS: Final = 0
RAR5_OS_UNIX: Final = 1

DOS_MODE_ARCHIVE: Final = 0x20
DOS_MODE_DIR: Final = 0x10
DOS_MODE_SYSTEM: Final = 0x04
DOS_MODE_HIDDEN: Final = 0x02
DOS_MODE_READONLY: Final = 0x01

RAR5_PW_CHECK_SIZE: Final = 8
RAR5_PW_SUM_SIZE: Final = 4

##
## internal constants
##

RAR_ID: Final = b"Rar!\x1a\x07\x00"
RAR5_ID: Final = b"Rar!\x1a\x07\x01\x00"

RAR_V3: Final = 3
RAR_V5: Final = 5

__all__ = (
    "RAR_BLOCK_MARK", "RAR_BLOCK_MAIN", "RAR_BLOCK_FILE", "RAR_BLOCK_OLD_COMMENT",
    "RAR_BLOCK_OLD_EXTRA", "RAR_BLOCK_OLD_SUB", "RAR_BLOCK_OLD_RECOVERY",
    "RAR_BLOCK_OLD_AUTH", "RAR_BLOCK_SUB", "RAR_BLOCK_ENDARC",
    "RAR_MAIN_VOLUME", "RAR_MAIN_COMMENT", "RAR_MAIN_LOCK", "RAR_MAIN_SOLID",
    "RAR_MAIN_NEWNUMBERING", "RAR_MAIN_AUTH", "RAR_MAIN_RECOVERY", "RAR_MAIN_PASSWORD",
    "RAR_MAIN_FIRSTVOLUME", "RAR_MAIN_ENCRYPTVER",
    "RAR_FILE_SPLIT_BEFORE", "RAR_FILE_SPLIT_AFTER", "RAR_FILE_PASSWORD", "RAR_FILE_COMMENT",
    "RAR_FILE_SOLID", "RAR_FILE_DICTMASK", "RAR_FILE_DICT64", "RAR_FILE_DICT128",
    "RAR_FILE_DICT256", "RAR_FILE_DICT512", "RAR_FILE_DICT1024", "RAR_FILE_DICT2048",
    "RAR_FILE_DICT4096",
    "RAR_FILE_DIRECTORY", "RAR_FILE_LARGE", "RAR_FILE_UNICODE", "RAR_FILE_SALT",
    "RAR_FILE_VERSION", "RAR_FILE_EXTTIME", "RAR_FILE_EXTFLAGS",
    "RAR_ENDARC_NEXT_VOLUME", "RAR_ENDARC_DATACRC", "RAR_ENDARC_REVSPACE", "RAR_ENDARC_VOLNR",
    "RAR_SKIP_IF_UNKNOWN", "RAR_LONG_BLOCK",
    "RAR_OLD_SUB_OS2", "RAR_OLD_SUB_UNIX", "RAR_OLD_SUB_MAC", "RAR_OLD_SUB_BEOS",
    "RAR_OLD_SUB_NT", "RAR_OLD_SUB_STREAM",
    "RAR_OS_MSDOS", "RAR_OS_OS2", "RAR_OS_WIN32", "RAR_OS_UNIX",
    "RAR_OS_MACOS", "RAR_OS_BEOS",
    "RAR_M0", "RAR_M1", "RAR_M2", "RAR_M3", "RAR_M4", "RAR_M5",
    "RAR_MAX_PASSWORD", "RAR_MAX_KDF_SHIFT", "RAR_MAX_COMMENT",
    "RAR5_BLOCK_MAIN", "RAR5_BLOCK_FILE", "RAR5_BLOCK_SERVICE", "RAR5_BLOCK_ENCRYPTION", "RAR5_BLOCK_ENDARC",
    "RAR5_BLOCK_FLAG_EXTRA_DATA", "RAR5_BLOCK_FLAG_DATA_AREA", "RAR5_BLOCK_FLAG_SKIP_IF_UNKNOWN",
    "RAR5_BLOCK_FLAG_SPLIT_BEFORE", "RAR5_BLOCK_FLAG_SPLIT_AFTER",
    "RAR5_BLOCK_FLAG_DEPENDS_PREV", "RAR5_BLOCK_FLAG_KEEP_WITH_PARENT",
    "RAR5_MAIN_FLAG_ISVOL", "RAR5_MAIN_FLAG_HAS_VOLNR", "RAR5_MAIN_FLAG_SOLID",
    "RAR5_MAIN_FLAG_RECOVERY", "RAR5_MAIN_FLAG_LOCKED", "RAR5_FILE_FLAG_ISDIR",
    "RAR5_FILE_FLAG_HAS_MTIME", "RAR5_FILE_FLAG_HAS_CRC32", "RAR5_FILE_FLAG_UNKNOWN_SIZE",
    "RAR5_COMPR_SOLID", "RAR5_ENC_FLAG_HAS_CHECKVAL", "RAR5_ENDARC_FLAG_NEXT_VOL",
    "RAR5_XFILE_ENCRYPTION", "RAR5_XFILE_HASH", "RAR5_XFILE_TIME", "RAR5_XFILE_VERSION",
    "RAR5_XFILE_REDIR", "RAR5_XFILE_OWNER", "RAR5_XFILE_SERVICE",
    "RAR5_XTIME_UNIXTIME", "RAR5_XTIME_HAS_MTIME", "RAR5_XTIME_HAS_CTIME",
    "RAR5_XTIME_HAS_ATIME", "RAR5_XTIME_UNIXTIME_NS",
    "RAR5_XENC_CIPHER_AES256", "RAR5_XENC_CHECKVAL", "RAR5_XENC_TWEAKED",
    "RAR5_XHASH_BLAKE2SP",
    "RAR5_XREDIR_UNIX_SYMLINK", "RAR5_XREDIR_WINDOWS_SYMLINK", "RAR5_XREDIR_WINDOWS_JUNCTION",
    "RAR5_XREDIR_HARD_LINK", "RAR5_XREDIR_FILE_COPY", "RAR5_XREDIR_ISDIR",
    "RAR5_XOWNER_UNAME", "RAR5_XOWNER_GNAME", "RAR5_XOWNER_UID", "RAR5_XOWNER_GID",
    "RAR5_OS_WINDOWS", "RAR5_OS_UNIX",
    "DOS_MODE_ARCHIVE", "DOS_MODE_DIR", "DOS_MODE_SYSTEM", "DOS_MODE_HIDDEN", "DOS_MODE_READONLY",
    "RAR5_PW_CHECK_SIZE", "RAR5_PW_SUM_SIZE",
    "RAR_ID", "RAR5_ID", "RAR_V3", "RAR_V5",
)
