Archive: test/files/rar5-symlink-unix.rar
R5_FILE: hdrlen=55 datlen=0 hdr_extra=24 is=--L
  block_flags=0x0003:EXTRA,DATA
  name=data_link
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=8 solid=False
  os=1:UNIX mode=lrwxrwxrwx cmp=0 dec=8 vol=0
  crc=0x00000000 (0)
  date_time=2020-07-26 20:13:58
  mtime=2020-07-26T20:13:58.125453113+00:00
  redir: type=UNIX_SYMLINK flags=0:- destination=data.txt
R5_FILE: hdrlen=43 datlen=5 hdr_extra=11 is=F--
  block_flags=0x0003:EXTRA,DATA
  name=data.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=8 solid=False
  os=1:UNIX mode=-rw-rw-r-- cmp=5 dec=5 vol=0
  crc=0xe6c1c582 (3871458690)
  date_time=2020-07-26 20:13:33
  mtime=2020-07-26T20:13:33.568312816+00:00
R5_FILE: hdrlen=61 datlen=0 hdr_extra=28 is=--L
  block_flags=0x0003:EXTRA,DATA
  name=random_link
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=8 solid=False
  os=1:UNIX mode=lrwxrwxrwx cmp=0 dec=12 vol=0
  crc=0x00000000 (0)
  date_time=2020-07-26 20:32:08
  mtime=2020-07-26T20:32:08.896575845+00:00
  redir: type=UNIX_SYMLINK flags=0:- destination=../random123
