Archive: test/files/rar5-readonly-win.rar
FILE: hdrlen=55 datlen=9 is=F--
  flags=0x9020:EXTTIME,LONG,D128
  os=2:WIN ver=29 mode=READONLY,ARCHIVE meth=0 cmp=9 dec=9 vol=0
  crc=0x818d2276 (2173510262) date_time=2020-07-26 22:11:42
  name=ro_dir/ro_file.txt
  mtime=2020-07-26T22:11:42.312616300
FILE: hdrlen=43 datlen=0 is=-D-
  flags=0x90e0:EXTTIME,LONG,DIR
  os=2:WIN ver=20 mode=READONLY,DIRECTORY meth=0 cmp=0 dec=0 vol=0
  crc=0x00000000 (0) date_time=2020-07-26 22:11:42
  name=ro_dir/
  mtime=2020-07-26T22:11:42.328617
