#
# https://docs.github.com/en/actions
# https://github.com/actions
#
# https://formulae.brew.sh/
# https://packages.msys2.org/
#

name: CI

on:
  pull_request: {}
  push: {}

jobs:

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39

      - name: "Setup Python ${{matrix.pick.PY}}"
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: "Run Lint"
        run: |
          make lint

      - name: "Run Docs"
        run: |
          make docs

  test:
    name: |
      Test - ${{ matrix.pick.OS }} / ${{ matrix.pick.PYNAME }}${{
        matrix.pick.CRYPTO != '' && format(' / {0}', matrix.pick.CRYPTO) || ''
      }}
    runs-on: ${{matrix.pick.OS}}
    strategy:
      fail-fast: false
      matrix:
        pick:
          - {OS: "ubuntu-latest", PY: "3.10", PYNAME: "Python 3.10", CRYPTO: ""}
          - {OS: "ubuntu-latest", PY: "3.10", PYNAME: "Python 3.10", CRYPTO: "pycryptodome"}
          - {OS: "ubuntu-latest", PY: "3.10", PYNAME: "Python 3.10", CRYPTO: "cryptography"}
          - {OS: "ubuntu-latest", PY: "3.11", PYNAME: "Python 3.11", CRYPTO: "cryptography"}
          - {OS: "ubuntu-latest", PY: "3.12", PYNAME: "Python 3.12", CRYPTO: "cryptography"}
          - {OS: "ubuntu-latest", PY: "3.13", PYNAME: "Python 3.13", CRYPTO: "cryptography"}
          - {OS: "ubuntu-latest", PY: "3.14", PYNAME: "Python 3.14", CRYPTO: "cryptography"}
          - {OS: "ubuntu-latest", PY: "3.14t", PYNAME: "Python 3.14t", CRYPTO: "cryptography"}
          - {OS: "macos-latest", PY: "3.13", PYNAME: "Python 3.13", CRYPTO: "cryptography"}
          - {OS: "macos-latest", PY: "3.14", PYNAME: "Python 3.14", CRYPTO: "cryptography"}
          - {OS: "windows-latest", PY: "3.12", PYNAME: "Python 3.12", CRYPTO: "cryptography" }
          - {OS: "windows-latest", PY: "3.14", PYNAME: "Python 3.14", CRYPTO: "cryptography" }
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39

      - name: "Setup ${{matrix.pick.PYNAME}}"
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.pick.PY}}

      - name: "Install archivers (linux)"
        if: ${{runner.os == 'Linux'}}
        run: |
          sudo -nH apt-get -qqy install unrar unar libarchive-tools p7zip-rar
          unrar
          unar -h
          bsdtar -h
          7z i

      - name: "Install archivers (macos)"
        if: ${{runner.os == 'macOS'}}
        run: |
          brew install rar unar libarchive sevenzip
          unrar
          unar -h
          bsdtar -h
          7z i
          7zz i

      - name: "Install archivers (windows)"
        if: ${{runner.os == 'Windows'}}
        shell: cmd
        run: |
          set "PATH=c:\msys64\usr\bin;%PATH%"
          pacman -S --noconfirm --needed bsdtar p7zip
          curl -sS -o unrarw64.exe https://www.rarlab.com/rar/unrarw64.exe
          7z x unrarw64.exe
          unrar
          bsdtar -h
          7z i

      - name: Run tests
        shell: bash
        run: |
          make test PYTHON="${{ matrix.pick.PY }}" CRYPTO="${{ matrix.pick.CRYPTO }}"
